service: AWS-gateway
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-east-1

functions:
  sayMyName:
    handler: src/index.sayMyName
    events:
      - httpApi:
          path: /sayMyName
          method: post
  convertCoins:
    handler: src/index.convertCoins
    events:
      - httpApi:
          path: /convertCoins
          method: post